# Generated by Django 3.2.6 on 2022-01-09 05:29

from django.db import migrations, models
import posts.image_upload_helper


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20211107_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=posts.image_upload_helper.upload_thread_image),
        ),
    ]
