# Generated by Django 3.2.6 on 2022-01-10 05:53

from django.db import migrations, models
import posts.image_upload_helper


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_thread_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=posts.image_upload_helper.upload_post_image),
        ),
    ]
