# Generated by Django 3.2.6 on 2022-01-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(default='test', max_length=500),
            preserve_default=False,
        ),
    ]
