# Generated by Django 3.2.6 on 2022-02-07 13:31

from django.db import migrations, models
import users.image_upload_helper


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_husband_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=users.image_upload_helper.upload_user_image),
        ),
    ]
